CREATE TABLE [dbo].[remit_record]
(
	[id] INT NOT NULL PRIMARY KEY identity(1,1),
	[user_id] INT NOT NULL,
	[arc_name] nvarchar(255) NOT NULL,
	[arc_no] nvarchar(255) NOT NULL,
	[payee_type] INT NOT NULL,
	[id_image_a] nvarchar(512) NOT NULL DEFAULT '',
	[id_image_b] nvarchar(512) NOT NULL DEFAULT '',
	[id_image_c] nvarchar(512) NOT NULL,
	[real_time_pic] nvarchar(512) NOT NULL,
	[e-signature] nvarchar(max),
	[create_time] datetime NULL DEFAULT GETDATE(),
	[update_time] datetime NULL DEFAULT GETDATE(),
	[from_currency_id] int NOT NULL,
	[to_currency_id] int NOT NULL,
	[from_amount] int NOT NULL,
	[apply_exchange_rate] float NOT NULL,
	[transaction_exchange_rate] float NOT NULL,
	[fee] float,
	[fee_type] int NOT NULL,
	[discount_id] int DEFAULT NULL,
	[discount_amount] float DEFAULT NULL,
	[beneficiar_id] int DEFAULT NULL,
	[transaction_status] int  NOT NULL,
	[arc_status]  int  DEFAULT 0,
	[arc_verify_time] datetime NULL DEFAULT GETDATE(),
	[payment_time] datetime NULL DEFAULT GETDATE(),
	[payment_code] nvarchar(200) null,
	[is_draft] int NOT NULL DEFAULT 1,
)
